### ISSUE TITLE
ConformanceQuickbufTest failure on JDK8, Tag 1.3.3

### ISSUE THREAD

**Issue by yinfeifan** [HebiRobotics/QuickBuffers#67] opened 2024-01-29 05:18 UTC
[ERROR] Failures:
[ERROR]   ConformanceQuickbufTest.testValidDataRepeatedEnumPacked:45->assertEqualsProto2:77 Recommended.Proto2.ProtobufInput.ValidDataRepeated.ENUM.PackedInput.PackedOutput.ProtobufOutput: arrays first differed at element [10]; expected:<-1> but was:<-113>

**Comment by ennerf** [comment] 2024-01-31 22:44
Conformance tests on CI run as expected. Closing because I can't reproduce it.

**Closed by ennerf** 2024-01-31 22:44 UTC
